package Velazquez;

import java.awt.image.BufferedImage;
import java.io.File;
import uk.co.caprica.vlcj.player.embedded.EmbeddedMediaPlayer;
import uk.co.caprica.vlcj.component.EmbeddedMediaPlayerComponent;
import uk.co.caprica.vlcj.player.MediaPlayerEventListener;
/**
 * Ventana interna al escritorio de la ventana principal dedicada a reproduccion de video.
 * @author gervi
 */
public class VentanaInternaVideo extends javax.swing.JInternalFrame {


    /**
     * Reproductor de video.
     */
    public EmbeddedMediaPlayer vlcplayer = null;
    /**
     * Archivo de video.
     */
    private File fMedia;
    
    /**
     * Constructor por defecto, añade un vídeo a la ventana interna
     * @param f archivo de vídeo
     */
    public VentanaInternaVideo(File f) {

        initComponents();
        fMedia = f;
        EmbeddedMediaPlayerComponent aVisual = new EmbeddedMediaPlayerComponent();
        getContentPane().add(aVisual,java.awt.BorderLayout.CENTER);
        vlcplayer = aVisual.getMediaPlayer();
        
    }
    
    /**
     * Método que llama internamente al constructor en caso de error al crear
     * el Player, devuelve null
     * 
     * @param f archivo de vídeo
     * @return devuelve null en caso de error
     */
    public static VentanaInternaVideo getInstance(File f){
        VentanaInternaVideo v = new VentanaInternaVideo(f);
        return (v.vlcplayer!=null?v:null);
    }
    /**
     * Inicia la reproducción del vídeo
     */
    public void play() {
        if (vlcplayer != null) {
            if (vlcplayer.isPlaying()) {
                vlcplayer.pause();
            }
            else{
                if(vlcplayer.isPlayable()){
                    vlcplayer.play();
                }
                else {
                    vlcplayer.playMedia(fMedia.getAbsolutePath());
                }
            }
        }
    }
    /**
     * Detiene la reproducción del vídeo
     */
    public void stop() {
        if (vlcplayer != null) {
            vlcplayer.stop();
        }
    }
    public void addMediaPlayerEventListener(MediaPlayerEventListener ml) {
        if (vlcplayer != null) {
            vlcplayer.addMediaPlayerEventListener(ml);
        }
    }
    /**
     * Devuelve una imagen de una captura de pantalla de lo que haya en la ventana.
     * @return devuelve la imagen capturada.
     */
    public BufferedImage getImagen(){
        BufferedImage img = vlcplayer.getSnapshot();
        return img;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setClosable(true);
        addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                formPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Cierra la camara cuando esta ventana se cierra.
     * @param evt: Objeto de evento de tipo PropertyChangeEvent.
     */
    private void formPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_formPropertyChange
        if(evt.getPropertyName().equals("closed")){
            stop();
            vlcplayer = null;
        }
    }//GEN-LAST:event_formPropertyChange


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
